### ISSUE TITLE
How to search snow-fort.org?

### ISSUE THREAD

**Issue by poldy** [sethalves/snow2-client#3]
Although the default repository has a decent collection of packages, snow-fort.org seems to have more. From "snow2 -h", it should be possible to pass some -r argument to search this site instead. However, the following both failed:

```sh
snow2 -r http://snow-fort.org/ search
snow2 -r http://snow-fort.org/pkg/ search
```

The error message is at the end of this issue report.

I checked, and there is no index.scm at either of these locations either, which I would expect.

Do you have any idea how to do this, or is there some incompatibility between snow2 and snow-fort.org that I don't understand? Thanks.

(I'm using Sagittarius Scheme 0.9.3 on macOS, with pull request #2 .)

```
Warning: unable to fetch repository index: "http://snow-fort.org/pkg/"
"http error during read response"
(#<condition
 #<&error>
 #<&message http error calling reader>
 #<&irritants (#<condition
 #<&error>
 #<&message Assertion failed>
 #<&irritants ((list? repository-sexp) #f)>
 #<stack-trace cause=#f>
>)>
 #<stack-trace cause=#f>
>)
Unhandled exception
  Condition components:
  1. &error
  2. &message Assertion failed
  3. &irritants ((snow2-repository? repository) #f)
  4. &stack-trace

stack trace:
  [1] error
  [2] caching-get-repository
    src: (error "Assertion failed" `(snow2-repository? repo
  [3] main-program
  [4] eval
  [5] main-loop
  [6] dynamic-wind
  [7] script
```

**Comment by poldy** [comment]
Sorry for the noise, but I just figured this out myself. From reading https://github.com/ashinn/snow-fort the argument required is "http://snow-fort.org/pkg/repo/". Searching works now.

Hopefully this will help someone else in future.

**Comment by sethalves** [comment]
I've added the Snow Fort repository to the list of siblings in snow2-client's default repository.
